# Реализация метода прогонки

##Импорты
Библиотека `numpy` используется только для удобства вывода результатов и употребляется только внутри функции `print()`

In [59]:
import numpy as np

## Инициализация матрицы и правой части

In [62]:
a = [-1, 1, 1]
b = [1, 1, 1, 1]
c = [1, 1, 1]
f = [1, 1, 1, 1]
n = len(b)
print("Ax = f\n\nA =\n", np.diag(a, -1) + np.diag(b, 0) + np.diag(c, 1), "\nf = \n", np.array(f)[:, None])

Ax = f

A =
 [[ 1  1  0  0]
 [-1  1  1  0]
 [ 0  1  1  1]
 [ 0  0  1  1]] 
f = 
 [[1]
 [1]
 [1]
 [1]]


## Прямой ход

In [63]:
c.append(0)
c[0] = c[0]/b[0]
f[0] = f[0]/b[0]
for j in range(1, n):
    c[j] = c[j]/(b[j]-a[j-1]*c[j-1])
    f[j] = (f[j]-a[j-1]*f[j-1])/(b[j]-a[j-1]*c[j-1])

## Обратный ход

In [64]:
x = [0 for j in range(n)]
x[-1] = f[-1]
for j in range(1, n):
    x[-j-1] = f[-j-1] - c[-j-1]*x[-j]

## Ответ

In [65]:
print("x = \n", np.array(x)[:, None])

x = 
 [[ 1.]
 [ 0.]
 [ 2.]
 [-1.]]
